name: Webapp CI

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - run: docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: builders

      - name: "Add Metadata"
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: koustubh/babybucks
          flavor: |
            latest=auto
          tags: |
            type=sha,
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=edge,branch=$repo.default_branch

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
